export const ADMIN_EN: Record<string, string> = {
  "管理画面": "Admin panel",
  "管理者のみアクセスできます": "Admins only",
  // タブ
  "出席記録": "Attendance",
  "出席簿": "Ledger",
  "会員管理": "Members",
  "レポート": "Report",
  "変更・休講": "Changes & closures",
  "お知らせ": "Announcements",
  "ブログ": "Blog",
  "個別メッセージ": "Direct message",
  "サーバーDB": "Server DB",
  "trial会員への一斉送信": "Broadcast to trial members",

  // 出席を記録する
  "出席を記録する": "Record attendance",
  "レッスン日": "Lesson date",
  "レッスン種別": "Lesson type",
  "個人レッスン時間": "Private lesson length",
  "レッスンを選択": "Select a lesson",
  "生徒を選択": "Select students",
  "未来の日付は記録できません": "Future dates cannot be recorded",
  "この日はレッスンがありません": "There are no lessons on this day",
  "レッスンを選択してください": "Please select a lesson",
  "生徒を選択してください": "Please select at least one student",
  "一部の記録に失敗しました": "Some records could not be saved",
  "記録する": "Record",
  "記録中...": "Recording...",
  "（講師）": "(teacher)",
  "（維持費含む）": "(incl. studio fee)",
  "バレエ": "Ballet",
  "モダン": "Modern",
  "ペア": "Pair",
  "レッスン": "Lesson",
  "維持費": "Studio fee",
  "合計": "Total",
  "名前なし": "No name",
  "（名前なし）": "(no name)",

  // 出席簿・会員
  "この日のデータがありません": "No data for this day",
  "この期間のデータがありません": "No data for this period",
  "名前で検索...": "Search by name...",
  "管理者": "Admin",
  "一般": "Regular",
  "バッジ": "Badges",
  "編集": "Edit",
  "削除": "Delete",
  "姓": "Last name",
  "名": "First name",
  "管理者 → 一般 に変更しますか？": "Change Admin → Regular?",
  "管理者に変更するには「admin」と入力してください": "Type “admin” to make this person an admin",
  "入力が正しくありません": "That input is not correct",
  "週間": "Weekly",
  "月間": "Monthly",
  "この記事を削除しますか？": "Delete this post?",

  // メッセージ
  "送信するメッセージを入力...": "Type your message...",
  "送信中...": "Sending...",
  "個別メッセージを送る": "Send a direct message",
  "メッセージを入力してください": "Please enter a message",
  "送信先を選択してください": "Please select recipients",
  "エラーが発生しました": "An error occurred",

  // サーバーDB
  "サーバーDB費用": "Server & database costs",
  "データがありません": "No data",
  "年月": "Month",
  "金額": "Amount",
  "受領日": "Received on",
  "未定": "TBD",
  "未受領": "Not received",

  // お知らせ・HP
  "お知らせを投稿する": "Post an announcement",
  "タイトル（必須）": "Title (required)",
  "本文（省略可）": "Body (optional)",
  "休講・振替": "Closure / substitute",
  "祝日レッスン": "Public holiday lesson",
  "イベント": "Event",
  "投稿済みのお知らせ": "Posted announcements",
  "お知らせはありません": "No announcements",
  "投稿する": "Post",
  "投稿中...": "Posting...",
  "投稿しました": "Posted",
  "投稿しました（HP・マイページ両方）": "Posted (website and My Page)",
  "投稿に失敗しました": "Could not post",
  "このお知らせを削除しますか？": "Delete this announcement?",
  "エラー:": "Error:",

  // ブログ
  "記事一覧": "Posts",
  "＋ 新規投稿": "+ New post",
  "記事がありません": "No posts",
  "← 一覧に戻る": "← Back to list",
  "SEO記事": "SEO article",
  "日記": "Diary",
  "公開中": "Published",
  "下書き": "Draft",
  "公開する": "Publish",
  "カテゴリなし": "No category",
  "カテゴリ管理": "Categories",
  "カテゴリ名（例：バレエ初心者ガイド）": "Category name (e.g. Beginner ballet guide)",
  "スラッグ（例：ballet-beginner）": "Slug (e.g. ballet-beginner)",
  "パーマリンク（例：adult-ballet-beginner-guide）": "Permalink (e.g. adult-ballet-beginner-guide)",
  "メタディスクリプション（検索結果に表示される説明文・120字以内）": "Meta description (shown in search results, up to 120 characters)",
  "サムネイル画像": "Thumbnail image",
  "画像を選択": "Choose image",
  "タイトルを入力してください": "Please enter a title",
  "メタディスクリプションは120字以内にしてください": "Keep the meta description within 120 characters",
  "名前とスラッグを入力してください": "Please enter a name and a slug",
  "追加しました": "Added",
  "失敗しました": "Failed",
  "保存しました": "Saved",
  "保存に失敗しました": "Could not save",
  "このカテゴリを削除しますか？": "Delete this category?",

  // 変更・休講
  "祝日・変更・不定期レッスン": "Public holiday, changed and irregular lessons",
  "休講": "Closures",
  "変更・臨時レッスンの内容を入力\n（空欄の場合「お知らせなし」と表示されます）": "Enter the details of changed or extra lessons\n(If empty, “No announcements” is shown)",
  "休講の内容を入力\n（空欄の場合「お知らせなし」と表示されます）": "Enter the closure details\n(If empty, “No announcements” is shown)",
  "クリア": "Clear",

  // エディタ
  "📷 画像": "📷 Image",
  "📷 画像を挿入": "📷 Insert image",
  "リンク": "Link",
  "1. リスト": "1. List",
  "• リスト": "• List",
  "URLを入力してください": "Enter a URL",

  // 会員の区分（変更確認の表示用）
  "体験": "Trial",

  // 祝日の名前（@holiday-jp が返す日本語）
  "元日": "New Year's Day",
  "成人の日": "Coming of Age Day",
  "建国記念の日": "National Foundation Day",
  "天皇誕生日": "The Emperor's Birthday",
  "春分の日": "Vernal Equinox Day",
  "昭和の日": "Showa Day",
  "憲法記念日": "Constitution Memorial Day",
  "みどりの日": "Greenery Day",
  "こどもの日": "Children's Day",
  "海の日": "Marine Day",
  "山の日": "Mountain Day",
  "敬老の日": "Respect for the Aged Day",
  "秋分の日": "Autumnal Equinox Day",
  "スポーツの日": "Sports Day",
  "文化の日": "Culture Day",
  "勤労感謝の日": "Labor Thanksgiving Day",
  "休日": "Substitute holiday",
  "振替休日": "Substitute holiday",
  "国民の休日": "Citizens' holiday",

  // サーバーが返すエラー
  "必須項目が不足しています": "Required fields are missing",
  "サーバーエラーが発生しました": "A server error occurred",
  "サーバーエラーが発生しました。": "A server error occurred.",
};
