// 体験レッスン・見学の申込みフォームと会員登録フォーム
export const FORMS_EN: Record<string, string> = {
  "申込みフォーム": "Booking form",
  "見学・体験レッスン": "Studio visit & trial lesson",
  "高田馬場・東中野・落合・新宿エリアにある「質問できる大人バレエ教室」 Y-de-ONE（ワイデワン）の体験レッスン・レッスン見学お申込みページです。":
    "Book a trial lesson or a free studio visit at Y-de-ONE, the adult ballet school where you can ask questions, in Takadanobaba, Tokyo.",
  "さん、Y-de-ONEに興味をもっていただきありがとうございます。": ", thank you for your interest in Y-de-ONE.",
  "申込み種別": "What would you like to book?",
  "レッスン見学（無料）": "Studio visit (free)",
  "体験レッスンの種類": "Trial lesson type",
  "モダンバレエ": "Modern Ballet",
  "体験レッスン希望日時": "Preferred trial lesson date and time",
  "見学希望日時": "Preferred studio visit date and time",
  "先に「体験レッスンの種類」を選択してください。": "Please choose the trial lesson type first.",
  "現在お選びいただける日時がありません。お手数ですがお問い合わせください。": "No dates are available right now. Please contact us.",
  "さらに日程を表示": "Show more dates",
  "希望の日時がない場合": "If none of these dates suit you",
  "（曜日・時間帯を伝える）": "(tell us the days and times you prefer)",
  "ご希望をお聞きして、スタッフから改めて日程をご案内します": "We will hear what you prefer and our staff will get back to you with a date",
  "ご希望の曜日・時間帯": "Preferred days and times",
  "例）水曜19時以降 / 土日の午前中を希望 など": "e.g. Wednesdays after 19:00 / weekend mornings",
  "氏名": "Full name",
  "例）山田花子": "e.g. Hanako Yamada",
  "バレエ経験": "Ballet experience",
  "はじめて": "Complete beginner",
  "少しだけ経験あり": "A little experience",
  "昔やっていた": "Danced in the past",
  "今も現役": "Still dancing",
  "ご質問・不安なことなど（任意）": "Questions or concerns (optional)",
  "例）服装について知りたい／子連れでも大丈夫か など": "e.g. What should I wear? Can I bring my child?",
  "例）服装・持ち物が知りたい／からだが硬いのが心配 など": "e.g. What should I bring? I am worried about being stiff",
  "必須": "Required",
  "この内容で日程を相談する": "Ask about a date with this request",
  "この内容で見学を申込む": "Book the studio visit",
  "この内容で体験レッスンを申込む": "Book the trial lesson",
  "読み込み中です…": "Loading…",
  "LINEログインに失敗しました。時間をおいて再度お試しください。": "Could not sign in with LINE. Please try again later.",

  // 送信後
  "ご希望ありがとうございます。\nスタッフが改めて日程をご案内いたします。": "Thank you for your request.\nOur staff will get back to you with a date.",
  "見学のお申込みありがとうございます。\n詳細はこの後LINEでご連絡いたします。": "Thank you for booking a studio visit.\nIn real life, we would send the details on LINE. (Demo: nothing is sent.)",
  "体験レッスンのお申込みありがとうございます。\n詳細はこの後LINEでご連絡いたします。": "Thank you for booking a trial lesson.\nIn real life, we would send the details on LINE. (Demo: nothing is sent.)",
  "氏名を入力してください。": "Please enter your name.",
  "体験レッスンの種類を選択してください。": "Please choose the trial lesson type.",
  "ご希望の曜日・時間帯を入力してください。": "Please enter your preferred days and times.",
  "希望日時を選択してください。": "Please choose a date and time.",
  "バレエ経験を選択してください。": "Please choose your ballet experience.",
  "送信中にエラーが発生しました。時間をおいて再度お試しください。": "Something went wrong. Please try again later.",
  "エラーが発生しました。": "An error occurred.",
  "必須項目が送信されていません。": "Required fields are missing.",

  // 会員登録
  "会員登録フォーム": "Member registration",
  "Y-de-ONE（ワイデワン）の会員登録ページです。": "Register as a member of Y-de-ONE.",
  "さん、お名前を登録してください。": ", please register your name.",
  "例）山田": "e.g. Yamada",
  "例）花子": "e.g. Hanako",
  "登録する": "Register",
  "登録が完了しました！": "Registration complete!",
  "Y-de-ONEへようこそ！": "Welcome to Y-de-ONE!",
  "すでに会員登録済みです。": "You are already registered.",
  "このアカウントは会員登録の対象外です。": "This account cannot be registered as a member.",
  "登録に失敗しました。": "Registration failed.",
  "サーバーエラーが発生しました。": "A server error occurred.",
};
