export const MYPAGE_EN: Record<string, string> = {
  "閉じる ▲": "Close ▲",
  "本文を表示 ▼": "Show text ▼",
  "リアクション": "Reactions",
  "ゲスト": "Guest",
  "名前を変更": "Change your name",
  "表示名を入力": "Enter a display name",
  "バッジの仕組み": "How badges work",
  "回数の数え方 ›": "How lessons are counted ›",
  "‹ 戻る": "‹ Back",
  "回数の数え方": "How lessons are counted",
  "🎉 バッジを獲得しました！": "🎉 You earned a badge!",
  "やったー！": "Yay!",
  "お知らせ": "Announcements",
  "レッスン履歴": "Lesson history",
  "マイバッジ": "My badges",
  "お知らせはありません": "No announcements",
  "この月の履歴がありません": "No lessons this month",
  "月1回以上": "1+ lessons a month",
  "月4回以上": "4+ lessons a month",
  "月8回以上": "8+ lessons a month",
  "月12回以上": "12+ lessons a month",
  "月20回以上": "20+ lessons a month",
  "月40回以上": "40+ lessons a month",
  "1回": "1 lesson",
  "0.5回": "0.5 lesson",
  "個人レッスン 15分": "Private lesson, 15 min",
};
