-- Demo database schema.
-- Mirrors the production "public" tables the app uses (columns, defaults, keys).
-- Safe to re-run. Apply to the DEMO Supabase project only.

create table if not exists users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  line_user_id text not null unique,
  name text not null,
  status text not null default 'trial',
  is_admin boolean not null default false,
  line_display_name text,
  line_picture_url text,
  mypage_picture_url text,
  mypage_name text,
  current_badge text,
  badge_notified boolean not null default true
);

create table if not exists attendances (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_id bigint not null references users (id),
  lesson_date date not null,
  lesson_type text not null,
  price_paid integer not null default 0,
  lesson_title text,
  lesson_time text,
  lesson_teacher text
);
create index if not exists attendances_student_date_idx on attendances (student_id, lesson_date);
create index if not exists attendances_lesson_date_idx on attendances (lesson_date);

create table if not exists badges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id bigint not null references users (id),
  year_month text not null,
  badge text not null,
  notified boolean not null default false,
  unique (user_id, year_month)
);

create table if not exists notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  is_active boolean default true,
  created_at timestamptz default now(),
  author text
);

create table if not exists reactions (
  id bigint generated by default as identity primary key,
  notice_id bigint not null references notices (id),
  user_id bigint not null references users (id),
  emoji text not null,
  created_at timestamptz default now()
);
create index if not exists reactions_notice_idx on reactions (notice_id);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  created_at timestamptz not null default now()
);

create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null default '',
  type text not null default 'diary',
  status text not null default 'draft',
  thumbnail_url text,
  meta_description text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  slug text,
  category_id bigint
);

create table if not exists hp_news (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null default '',
  category text,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists lesson_info (
  section text primary key,
  content text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists server_db_costs (
  id serial primary key,
  year_month text not null unique,
  amount integer,
  received_at date,
  note text,
  created_at timestamptz default now()
);

-- The app reads and writes only through the server (service role key).
-- RLS on with no policies keeps the public anon key out.
alter table users enable row level security;
alter table attendances enable row level security;
alter table badges enable row level security;
alter table notices enable row level security;
alter table reactions enable row level security;
alter table categories enable row level security;
alter table posts enable row level security;
alter table hp_news enable row level security;
alter table lesson_info enable row level security;
alter table server_db_costs enable row level security;

-- Wipes every table and restarts the id counters. Called by the daily reset job
-- (app/api/cron/reset-demo) before it re-inserts the fictional data.
create or replace function demo_reset_data() returns void
language plpgsql security definer set search_path = public as $$
begin
  truncate table reactions, attendances, badges, notices, posts, categories,
    hp_news, lesson_info, server_db_costs, users restart identity;
end $$;
revoke all on function demo_reset_data() from public, anon, authenticated;
grant execute on function demo_reset_data() to service_role;

-- Storage buckets used by the app (public read; uploads go through the server).
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true), ('post-images', 'post-images', true)
on conflict (id) do nothing;

notify pgrst, 'reload schema';
